[[pages]]
path = "pages/Home.py"
name = "Home"

[[pages]]
path = "pages/DataExplore.py"
name = "Data Explore"

[[pages]]
path = "pages/BatteryViewer.py"
name = "Battery Viewer"

[[pages]]
path = "pages/Results.py"
name = "Regression Results"



